# Generated by Django 2.1.1 on 2018-10-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviepanel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentRanking',
        ),
        migrations.DeleteModel(
            name='MovieRanking',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
