# Generated by Django 2.1.1 on 2018-10-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviepanel', '0002_auto_20181004_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviecategory',
            options={'verbose_name': 'Movie Category', 'verbose_name_plural': 'Movie Categories'},
        ),
        migrations.AddField(
            model_name='moviecategory',
            name='moviepanel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moviecategories', related_query_name='moviecategory', to='moviepanel.MoviePanel'),
        ),
        migrations.AddField(
            model_name='moviecategory',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Movie Category'),
        ),
        migrations.AddField(
            model_name='moviecategory',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='moviepanel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Movie Panel'),
        ),
    ]
