# Generated by Django 2.1.1 on 2018-10-14 11:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('moviepanel', '0004_auto_20181013_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=112, null=True, verbose_name='Movie Category')),
                ('slug', models.SlugField(default='', max_length=112, unique=True)),
            ],
            options={
                'verbose_name': 'Movie Category',
                'verbose_name_plural': 'Movie Categories',
            },
        ),
        migrations.RemoveField(
            model_name='moviecategory',
            name='moviepanel',
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='movie',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='', max_length=512, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='movie',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='movie',
            name='moviepanel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', related_query_name='movie', to='moviepanel.MoviePanel'),
        ),
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, default='', upload_to='posters', verbose_name='Poster'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, default='', verbose_name='Poster URL'),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Release date'),
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(blank=True, default='', verbose_name='Trailer'),
        ),
        migrations.AlterField(
            model_name='moviepanel',
            name='name',
            field=models.CharField(max_length=112, null=True, verbose_name='Panel name'),
        ),
        migrations.AlterField(
            model_name='moviepanel',
            name='slug',
            field=models.SlugField(max_length=112, unique=True),
        ),
        migrations.DeleteModel(
            name='MovieCategory',
        ),
        migrations.AddField(
            model_name='moviegenre',
            name='moviepanel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moviecategories', related_query_name='moviegenre', to='moviepanel.MoviePanel'),
        ),
    ]
