# Generated by Django 2.1.1 on 2018-10-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepanel', '0006_auto_20181014_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters', verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='name',
            field=models.CharField(default='', max_length=112, verbose_name='Movie Genre'),
        ),
        migrations.AlterField(
            model_name='moviepanel',
            name='name',
            field=models.CharField(default='', max_length=112, verbose_name='Panel name'),
        ),
    ]
