# Generated by Django 2.1.1 on 2018-10-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepanel', '0007_auto_20181014_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='moviegenre',
            field=models.ManyToManyField(to='moviepanel.MovieGenre'),
        ),
    ]
