# Generated by Django 2.1.1 on 2018-10-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepanel', '0008_movie_moviegenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='moviegenre',
            field=models.ManyToManyField(related_name='movies', to='moviepanel.MovieGenre'),
        ),
    ]
