# Generated by Django 2.1.1 on 2018-10-15 12:37

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('moviepanel', '0009_auto_20181015_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='invisible', max_length=100, no_check_for_status=True),
        ),
    ]
