# Generated by Django 2.1.1 on 2018-10-15 13:39

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('moviepanel', '0010_movie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='published_at',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when={'visible'}),
        ),
    ]
