# Generated by Django 2.1.1 on 2018-11-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepanel', '0011_movie_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_scraped',
            field=models.BooleanField(default=False, verbose_name='Is scraped'),
        ),
    ]
