# Generated by Django 2.1.1 on 2018-11-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepanel', '0012_movie_is_scraped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(default='', max_length=1024, verbose_name='Description'),
        ),
    ]
