# Generated by Django 2.1.1 on 2018-11-06 14:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepanel', '0013_auto_20181106_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None),
        ),
    ]
