# Generated by Django 2.1.1 on 2018-11-06 14:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepanel', '0014_auto_20181106_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
