# Generated by Django 2.1.1 on 2018-11-06 15:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepanel', '0016_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='original_language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
