# Generated by Django 2.1.1 on 2018-11-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepanel', '0017_movie_original_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='seasons',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Seasons'),
        ),
    ]
