# Generated by Django 2.1.1 on 2018-11-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepanel', '0018_movie_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='seasons',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Seasons'),
        ),
    ]
