# Generated by Django 2.1.1 on 2018-11-08 14:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepanel', '0019_auto_20181106_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='yt_trailer_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=55), blank=True, default=list, size=None),
        ),
    ]
