# Generated by Django 2.1.1 on 2018-11-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviepanel', '0020_movie_yt_trailer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer',
        ),
    ]
