# Generated by Django 2.1.1 on 2018-11-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepanel', '0021_remove_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(blank=True, default='', verbose_name='Trailer url'),
        ),
    ]
