# Generated by Django 2.1.1 on 2018-11-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepanel', '0022_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_trailer_scraped',
            field=models.BooleanField(default=False, verbose_name='Is Trailer scraped'),
        ),
    ]
