# Generated by Django 2.1.1 on 2018-11-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepanel', '0024_remove_movie_is_trailer_scraped'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_yt_scraped',
            field=models.BooleanField(default=False, verbose_name='Is YouTube scraped'),
        ),
    ]
